Update to latest theia upstream (#609)
* feat(yarn): Regenerate yarn.lock to have latest changes
* fix(tsconfig): skip lib check to avoid the message

node_modules/@types/mocha/index.d.ts:2680:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'beforeEach' must be of type 'Lifecycle', but here has type 'HookFunction'.
2680 declare var beforeEach: Mocha.HookFunction;

* fix(tsconfig): Remove some links to external packages


* fix(jest): Update jest dependency to avoid handlebars error
Access has been denied to resolve the property "functions" because it is not an "own property" of its parent.

* fix(node): Stick to a given of mkdirp as the latest one is requiring nodejs >= 10

* fix: do not remove scm as it's used by plugin-ext now
* fix: update run goal to be theia build
* feat(generator): add compilation units used by eclipse che theia
* use lerna build on all packages